### ISSUE TITLE
Odoo Shell inside docker

### ISSUE THREAD

**Issue by abufikri** [minhng92/odoo-16-docker-compose#17]
Hi, currently I'm running your odoo-16-docker-compose, and it is running well and open normally via browser : http://localhost:10016

How can I go to Odoo shell, like I've read on odoo tutorial : 
$ odoo shell -c odoo.conf -d db_training

I've tried with this command : 
$ docker exec -it odoo16-docker-compose bash -c "odoo shell -c /etc/odoo/odoo.conf -d db_training"

but it gave an error : 
File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 64, in __new__
    return cls.registries[db_name]
  File "<decorator-gen-6>", line 2, in __getitem__
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'db_training'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/odoo", line 8, in <module>
    odoo.cli.main()
  File "/usr/lib/python3/dist-packages/odoo/cli/command.py", line 66, in main
    o.run(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/shell.py", line 123, in run
    self.shell(config['db_name'])
  File "/usr/lib/python3/dist-packages/odoo/cli/shell.py", line 109, in shell
    registry = odoo.registry(dbname)
  File "/usr/lib/python3/dist-packages/odoo/__init__.py", line 104, in registry
    return modules.registry.Registry(database_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 66, in __new__
    return cls.new(db_name)
  File "<decorator-gen-14>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 78, in new
    registry.init(db_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 159, in init
    with closing(self.cursor()) as cr:
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 852, in cursor
    return self._db.cursor()
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 740, in cursor
    return Cursor(self.__pool, self.__dbname, self.__dsn)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 267, in __init__
    self._cnx = pool.borrow(dsn)
  File "<decorator-gen-2>", line 2, in borrow
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 668, in borrow
    result = psycopg2.connect(
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?

**Comment by abufikri** [comment]
After Googling, I found solution :

docker exec -it <container-name> bash -c "odoo shell -c /etc/odoo/odoo.conf -d <DB_NAME> --db_host <HOSTNAME> --db_password <DB_PASSWORD> --db_user <DB_USER>"

or 

docker exec -it  odoo16-docker-compose bash -c "odoo shell -c /etc/odoo/odoo.conf -d db_training --db_host db --db_password odoo16@2022 --db_user odoo"

It works for me.
